import { NextPage } from "next";
import Head from "next/head";

const TestPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Test Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>TestPage</h1>
    </div>
  );
};

export default TestPage;
